import HeaderMain from "@/components/HeaderMain";
import HeaderTop from "@/components/HeaderTop";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop></HeaderTop>
        <HeaderMain></HeaderMain>
        {children}
        </body>
    </html>
  );
}
